name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dserikov/pied_piper:latest

    - name: Notify Slack
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message,commit,author
        custom_payload: '{"text":"Docker image build and push succeeded: ${{ github.repository }}:${{ github.sha }}"}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message,commit,author
        custom_payload: '{"text":"Docker image build and push failed: ${{ github.repository }}:${{ github.sha }}"}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
